WIP: full bash/ksh wildcard support: added translate() test patterns to check the code (it fails!)
Also moved several internal glob helper functions to the glob namespace, making them public: their prototypes have been added to glob.h

Test results for translate():

```
ERROR: translate("ab[--z]") --> "((ab[--z\--z])|[\r\n])$" instead of expected: "((ab[\--z])|[\r\n])$"
ERROR: translate("ab[%--]") --> "((ab[%--%\--])|[\r\n])$" instead of expected: "((ab[%-\-])|[\r\n])$"
ERROR: translate("ab[^1-9]") --> "((ab[\\^1-9])|[\r\n])$" instead of expected: "((ab[\^1-9])|[\r\n])$"
ERROR: translate("ab[a-]") --> "((ab[a-])|[\r\n])$" instead of expected: "((ab[a\-])|[\r\n])$"
ERROR: translate("ab[-a]") --> "((ab[-a])|[\r\n])$" instead of expected: "((ab[\-a])|[\r\n])$"
ERROR: translate("[][!]") --> "(([][!])|[\r\n])$" instead of expected: "(([\]\[\!])|[\r\n])$"
ERROR: translate("[]-]") --> "(([]-])|[\r\n])$" instead of expected: "(([\]\-])|[\r\n])$"
ERROR: translate("[!]a-]") --> "(([^]a-])|[\r\n])$" instead of expected: "(([^\]a\-])|[\r\n])$"
ERROR: translate("a[[?*\]") --> "((a[\\[?*\\])|[\r\n])$" instead of expected: "((a[\[\?\*\\])|[\r\n])$"
ERROR: translate("b[[?*\\]") --> "((b[\\[?*\\\])|[\r\n])$" instead of expected: "((b[\[\?\*\\])|[\r\n])$"
ERROR: translate("?(ab|cd|ef)") --> "((.\(ab\|cd\|ef\))|[\r\n])$" instead of expected: "(((ab|cd|ef)?)|[\r\n])$"
ERROR: translate("*(ab|cd|ef)") --> "((.*\(ab\|cd\|ef\))|[\r\n])$" instead of expected: "(((ab|cd|ef)*)|[\r\n])$"
ERROR: translate("@(ab|cd|ef)") --> "((@\(ab\|cd\|ef\))|[\r\n])$" instead of expected: "(((ab|cd|ef))|[\r\n])$"
ERROR: translate("!(ab|cd|ef)") --> "((!\(ab\|cd\|ef\))|[\r\n])$" instead of expected: "(((?!(ab|cd|ef)))|[\r\n])$"
ERROR: translate("**") --> "((.*.*)|[\r\n])$" instead of expected: "((.*)|[\r\n])$"
```